import { Role } from "@/types/permission.types";

export const defaultRoles: Role[] = [
  {
    id: 'super-admin',
    name: 'Super Admin',
    permissions: {
      // group-level
      asset: true,
      location: true,
      analytics: true,
      users: true,
      audit: true,
      settings: true,
      // asset
      'asset.upload': true,
      'asset.view': true,
      'asset.edit': true,
      'asset.download': true,
      // location
      'location.view': true,
      'location.edit': true,
      // analytics
      'analytics.create': true,
      'analytics.view': true,
      'analytics.edit': true,
      'analytics.download': true,
      // users
      'users.view': true,
      'users.edit': true,
      'users.add': true,
      // audit
      'audit.view': true,
      // settings
      'settings.edit': true,
      'settings.delete': true,
    },
  },
  {
    id: 'admin',
    name: 'Admin',
    permissions: {
      asset: true,
      location: true,
      analytics: true,
      users: true,
      audit: true,
      settings: true,
      'asset.upload': true,
      'asset.view': true,
      'asset.edit': true,
      'asset.download': true,
      'location.view': true,
      'location.edit': true,
      'analytics.create': true,
      'analytics.view': true,
      'analytics.edit': true,
      'analytics.download': true,
      'users.view': true,
      'users.edit': true,
      'users.add': true,
      'audit.view': true,
      'settings.edit': true,
      'settings.delete': false,
    },
  },
  {
    id: 'manager',
    name: 'Manager',
    permissions: {
      asset: true,
      location: true,
      analytics: true,
      users: false,
      audit: true,
      settings: true,
      'asset.upload': false,
      'asset.view': true,
      'asset.edit': false,
      'asset.download': true,
      'location.view': true,
      'location.edit': false,
      'analytics.create': false,
      'analytics.view': true,
      'analytics.edit': false,
      'analytics.download': false,
      'users.view': false,
      'users.edit': false,
      'users.add': false,
      'audit.view': true,
      'settings.edit': true,
      'settings.delete': false,
    },
  },
  {
    id: 'team-member',
    name: 'Team Member',
    permissions: {
      asset: true,
      location: true,
      analytics: true,
      users: false,
      audit: true,
      settings: true,
      'asset.upload': false,
      'asset.view': true,
      'asset.edit': false,
      'asset.download': true,
      'location.view': true,
      'location.edit': false,
      'analytics.create': false,
      'analytics.view': true,
      'analytics.edit': false,
      'analytics.download': false,
      'users.view': false,
      'users.edit': false,
      'users.add': false,
      'audit.view': false,
      'settings.edit': true,
      'settings.delete': false,
    },
  },
  {
    id: 'intern',
    name: 'Intern',
    permissions: {
      asset: false,
      location: true,
      analytics: true,
      users: false,
      audit: true,
      settings: true,
      'asset.upload': false,
      'asset.view': false,
      'asset.edit': false,
      'asset.download': false,
      'location.view': true,
      'location.edit': false,
      'analytics.create': false,
      'analytics.view': true,
      'analytics.edit': false,
      'analytics.download': false,
      'users.view': false,
      'users.edit': false,
      'users.add': false,
      'audit.view': false,
      'settings.edit': false,
      'settings.delete': false,
    },
  },
];



export const usersData = [
  { id: 1, name: 'Alice Johnson', email: 'alice.johnson@email.com', role: 'Super Admin' },
  { id: 2, name: 'Bob Smith', email: 'bob.smith@email.com', role: 'Admin' },
  { id: 3, name: 'Carol Williams', email: 'carol.williams@email.com', role: 'Manager' },
  { id: 4, name: 'David Brown', email: 'david.brown@email.com', role: 'Team Member' },
  { id: 5, name: 'Emma Davis', email: 'emma.davis@email.com', role: 'Intern' },
  { id: 6, name: 'Frank Miller', email: 'frank.miller@email.com', role: 'Admin' },
  { id: 7, name: 'Grace Wilson', email: 'grace.wilson@email.com', role: 'Manager' },
  { id: 8, name: 'Henry Moore', email: 'henry.moore@email.com', role: 'Team Member' },
  { id: 9, name: 'Ivy Taylor', email: 'ivy.taylor@email.com', role: 'Team Member' },
  { id: 10, name: 'Jack Anderson', email: 'jack.anderson@email.com', role: 'Intern' },
  { id: 11, name: 'Karen Thomas', email: 'karen.thomas@email.com', role: 'Manager' },
  { id: 12, name: 'Leo Jackson', email: 'leo.jackson@email.com', role: 'Admin' }
]
