import { Role } from "@/types/permission.types";

export const defaultRoles: Role[] = [
  {
    id: 'super-admin',
    name: 'Super Admin',
    permissions: {
      // group-level
      asset: true,
      location: true,
      analytics: true,
      users: true,
      audit: true,
      settings: true,
      // asset
      'asset.upload': true,
      'asset.view': true,
      'asset.edit': true,
      'asset.download': true,
      // location
      'location.view': true,
      'location.edit': true,
      // analytics
      'analytics.create': true,
      'analytics.view': true,
      'analytics.edit': true,
      'analytics.download': true,
      // users
      'users.view': true,
      'users.edit': true,
      'users.add': true,
      // audit
      'audit.view': true,
      // settings
      'settings.edit': true,
      'settings.delete': true,
    },
  },
  {
    id: 'admin',
    name: 'Admin',
    permissions: {
      asset: true,
      location: true,
      analytics: true,
      users: true,
      audit: true,
      settings: true,
      'asset.upload': true,
      'asset.view': true,
      'asset.edit': true,
      'asset.download': true,
      'location.view': true,
      'location.edit': true,
      'analytics.create': true,
      'analytics.view': true,
      'analytics.edit': true,
      'analytics.download': true,
      'users.view': true,
      'users.edit': true,
      'users.add': true,
      'audit.view': true,
      'settings.edit': true,
      'settings.delete': false,
    },
  },
  {
    id: 'manager',
    name: 'Manager',
    permissions: {
      asset: true,
      location: true,
      analytics: true,
      users: false,
      audit: true,
      settings: true,
      'asset.upload': false,
      'asset.view': true,
      'asset.edit': false,
      'asset.download': true,
      'location.view': true,
      'location.edit': false,
      'analytics.create': false,
      'analytics.view': true,
      'analytics.edit': false,
      'analytics.download': false,
      'users.view': false,
      'users.edit': false,
      'users.add': false,
      'audit.view': true,
      'settings.edit': true,
      'settings.delete': false,
    },
  },
  {
    id: 'team-member',
    name: 'Team Member',
    permissions: {
      asset: true,
      location: true,
      analytics: true,
      users: false,
      audit: true,
      settings: true,
      'asset.upload': false,
      'asset.view': true,
      'asset.edit': false,
      'asset.download': true,
      'location.view': true,
      'location.edit': false,
      'analytics.create': false,
      'analytics.view': true,
      'analytics.edit': false,
      'analytics.download': false,
      'users.view': false,
      'users.edit': false,
      'users.add': false,
      'audit.view': false,
      'settings.edit': true,
      'settings.delete': false,
    },
  },
  {
    id: 'intern',
    name: 'Intern',
    permissions: {
      asset: false,
      location: true,
      analytics: true,
      users: false,
      audit: true,
      settings: true,
      'asset.upload': false,
      'asset.view': false,
      'asset.edit': false,
      'asset.download': false,
      'location.view': true,
      'location.edit': false,
      'analytics.create': false,
      'analytics.view': true,
      'analytics.edit': false,
      'analytics.download': false,
      'users.view': false,
      'users.edit': false,
      'users.add': false,
      'audit.view': false,
      'settings.edit': false,
      'settings.delete': false,
    },
  },
];
